### ISSUE TITLE
[Feature Request] hide app address (FQDN) from the main page

### ISSUE THREAD

**Issue by vasyl83** [pawelmalak/flame#105]
I love Flame! The minimalistic look is great but one thing that bugs me if seeing the full fqdn under the app name. Would it be possible to all a toggle to disable it?

I have some very long domain names and it looks ugly on the otherwise pristine and clean interface.

Plus is it really necessary to see them? I know where the app leads as I was the one adding it. Also people other than me do not need to see the address, they only need to click on the app name.

**Comment by pawelmalak** [comment]
Duplicate of #99

**Comment by dinosmm** [comment]
> You can use this css to remove urls

Hi, this doesn't work with the recent update. Could you please suggest how to amend it to continue having the URLs hidden?

**Comment by Humschi** [comment]
> > You can use this css to remove urls
> 
> Hi, this doesn't work with the recent update. Could you please suggest how to amend it to continue having the URLs hidden?

You only need to change the class-selector
```CSS
.AppCard_AppCardDetails__HgNoY {
  height: 50%;
}

.AppCard_AppCardDetails__HgNoY span {
  display: none !important;
} 
```
