### ISSUE TITLE
Custom theme colors with custom CSS

### ISSUE THREAD

**Issue by schlaggi** [pawelmalak/flame#144]
Hello,

Can someone show me how to change the theme colors with custom CSS? I have close to zero CSS knowledge and my tries based on the CSS code from #115 were unsuccessful.
I really just want to set the base colors: --color-background/ --color-primary/ --color-accent

Thank you!

**Comment by pawelmalak** [comment]
You can set custom theme with this snippet:
```css
body {
  --color-primary: rgb(250, 177, 160) !important;
  --color-accent: rgba(255, 234, 167,1.0) !important;
  --color-background: #2d3436 !important;
}
```

Color values can be hex, rgb, rgba or css named colors. The only problem is that you can't change weather icon color.

Example custom theme using above snippet:

![screen](https://user-images.githubusercontent.com/24780509/140515926-f87052c7-95b0-46da-a9ee-6fb6c8410c56.png)
