### ISSUE TITLE
Docker image problem

### ISSUE THREAD

**Issue by Mape6** [pawelmalak/flame#162]
After updating my dockerized flame to the latest image, the container throws the following error:
```
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7e97a24c
```
I saw that the new image is about 500 MB smaller than the previous one.

**Comment by pawelmalak** [comment]
Which one? `latest` or `mulitarch`?

**Comment by Mape6** [comment]
> Which one? `latest` or `multiarch`?

Oh sorry that I forgot to mentioned that: multiarch

**Comment by pawelmalak** [comment]
Ok. And which platform architecture are you using: `ARMv7` or `ARMv8/ARM64`?

**Comment by Mape6** [comment]
`ARMv7` on a Raspberry Pi 2B

**Comment by pawelmalak** [comment]
It seems that this problem is only related to arm/v7. Multiarch image works fine on my desktop and on RPi4 arm64. I also have RPi Zero W but it's arm/v6 so I can't test on it.

**Comment by pawelmalak** [comment]
Also, have you tried building your own image and checking if it works?

**Comment by pawelmalak** [comment]
@Mape6 I pushed new `multiarch` tag. Can you check if anything has changed?

**Comment by phyber** [comment]
Seems to be failing with the same error here, with the new image pulled just moments before this comment:

```
$ docker-compose up
Pulling flame (pawelmalak/flame:multiarch)...
multiarch: Pulling from pawelmalak/flame
a14774a5a62e: Pull complete
2d39c4d1086c: Pull complete
d90eed824f13: Pull complete
05113b89d185: Pull complete
6048326a3b67: Pull complete
Digest: sha256:0fcc1f09656c7e9cd37b0aa8e345f377d87f87d3854df71702a837d56ee5255b
Status: Downloaded newer image for pawelmalak/flame:multiarch
Creating flame ... done
Attaching to flame
flame    |
flame    |
flame    | #
flame    | # Fatal error in , line 0
flame    | # unreachable code
flame    | #
flame    | #
flame    | #
flame    | #FailureMessage Object: 0xbed7c24c
flame exited with code 132
```

`docker-compose.yaml` is nothing special, mostly unrelated Traefik config:

```yaml
---
version: '2.1'

networks:
  traefik_default:
    external: true

services:
  flame:
    container_name: 'flame'
    image: 'pawelmalak/flame:multiarch'
    restart: 'unless-stopped'
    expose:
      - 5005
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.homer.entrypoints=web"
      - "traefik.http.routers.homer.rule=PathPrefix(`/`)"
    networks:
      - 'traefik_default'
    volumes:
      - './config:/app/data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
```
