### ISSUE TITLE
Cannot change password by adding environment variable in yaml file

### ISSUE THREAD

**Issue by Horuyuki** [pawelmalak/flame#178]
I am using docker-compose yaml to deploy this app, and upon adding the password as the wiki suggested:
```
    environment:
        - PASSWORD=wow_1234
```
I restarted the container and can not log in except with the default `flame_password`

Anyone else having the same issue?

**Comment by pawelmalak** [comment]
I'm using this docker-compose file and my new password is working fine:

```yml
version: '2.1'
services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    volumes:
      - /home/pi/dev/data/flame:/app/data
    ports:
      - 5005:5005
    environment:
      - PASSWORD=mypassword
    restart: unless-stopped
```
