### ISSUE TITLE
"docker restart" reset all datas

### ISSUE THREAD

**Issue by enzofoucaud** [pawelmalak/flame#196]
Hello,

I have a little problem when I do my docker-compose.
Maybe it's my fault but when I restart the container my datas are erased.

Below a part of my docker-compose.

```
version: '3.7'

networks:
  web:
    external: true
    name: web

services:
  flame:
    container_name: flame
    image: pawelmalak/flame:latest
    ports:
      - 5005:5005
    networks:
      - web
    volumes:
      - flame:/app/flame
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=testtest
    restart: unless-stopped
    labels:
      - traefikv2..

volumes:
  flame:
    name: flame
```
