### ISSUE TITLE
CSS Help please

### ISSUE THREAD

**Issue by ikrowni** [pawelmalak/flame#214]
Hello I've been trying for the past couple days to get the icon next to the bookmarks to change size. Could someone lend me some help with this? I've been successful at changing a lot of other aspects but this one I can't figure out. Thanks for any help.

**Comment by pawelmalak** [comment]
```css
.BookmarkCard_BookmarkIcon__2c2C5 .Icon_Icon__1Fl5u {
  transform: scale(1.5);
}
```
