### ISSUE TITLE
[Feature Request] - Being able to customize HTML

### ISSUE THREAD

**Issue by catalinchertes** [pawelmalak/flame#227]
Hey!

I recently deployed the app using docker and it is great, but I feel like something is missing... and that is the ability to customize subtle things about the html.

For example, I would like to add a placeholder to the search bar, because I feel like it's hard to tell that it is a search bar, so I would like to add something like Search... in the input field.

The second thing that I would like is to be able to change Applications to something else, just like we're able to edit header and welcome messages, it would be cool to be able to do the same with "Applications".

I searched like crazy trying to find the files to edit this myself but I am unable to find them, could you guide me to where this files are located and where I can make this changes myself?

Thank you very much.
Great work!

**Comment by pawelmalak** [comment]
Section names are in [Home.tsx](https://github.com/pawelmalak/flame/blob/master/client/src/components/Home/Home.tsx) on lines [105](https://github.com/pawelmalak/flame/blob/master/client/src/components/Home/Home.tsx#L105) and [127](https://github.com/pawelmalak/flame/blob/master/client/src/components/Home/Home.tsx#L127).

Search input is in [SearchBar.tsx](https://github.com/pawelmalak/flame/blob/master/client/src/components/SearchBar/SearchBar.tsx#L113)

**Comment by catalinchertes** [comment]
Where are the files located? Inside the docker container? I couldn't find them anywhere... I'm not that good with docker but doing a find -name with the file's name doesn't return anything.

**Comment by leonbeon** [comment]
You can do this with a bit of CSS trickery.  
Changing Applications/Bookmarks to something else:  

```css
a[href="/applications"] > h2,
a[href="/bookmarks"] > h2 {
    visibility: hidden;
}
a[href="/applications"] > h2::before {
    content: "Not Applications";
    visibility: visible;
}
a[href="/bookmarks"] > h2::before {
    content: "Not Bookmarks";
    visibility: visible;
}
```

Adding something in front of the search bar (not a placeholder, sadly):  
```css
#root > div:first-child > div:first-child {
    display: flex;
}
#root > div:first-child > div:first-child::before {
    content: "Search:";
    margin-bottom: 20px;
    margin-right: 0.33rem;
    padding: 10px 0;
    color: var(--color-accent);
}
```

I've chosen to select the elements based on DOM structure from `#root` or specificity (href attribute for anchors, for example). I think this will survive updates more than the auto generated class names, but I could be mistaken. In that case, selecting the search bar would be as simple as `SearchBar_SearchBar__2Pbl1::before`.
