### ISSUE TITLE
Only getting a purple screen

### ISSUE THREAD

**Issue by maeries** [pawelmalak/flame#24]
After deploying flame using this docker-compose file

```
version: '3'
services:
    flame:
        image: pawelmalak/flame:latest
        restart: unless-stopped
        volumes:
            - ./data:/app/data
        networks:
            - caddy_net

networks:
  caddy_net:
    external: true
```
I only get a purple screen when visiting the URL (I use Caddy2 as a reverse proxy). When I refresh the page I can see

```
Thursday 10, June 2021
Good Evening

Applications

Bookmarks
```
for a fraction of a second, before only the background color is shown again.

I tried Firefox and vivaldi and both show the same behaviour
