### ISSUE TITLE
[BUG]  Flame crashes after updating to version 2.1.1 while running on k3s.

### ISSUE THREAD

**Issue by jojotastic777** [pawelmalak/flame#242]
**Deployment details:**
- App version [e.g. v1.7.4]: v2.1.1
- Platform [e.g. amd64, arm64, arm/v7]: arm64, amd64
- Docker image tag [e.g. latest, multiarch]: multiarch2.1.1

---

**Bug description:**

After updating to version 2.1.1, my previously-working flame installation has started crashing with the following error:
```
node:internal/fs/utils:344
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at /app/node_modules/docker-secret/dist/index.js:17:39
    at Array.forEach (<anonymous>)
    at getSecrets (/app/node_modules/docker-secret/dist/index.js:14:15)
    at Object.<anonymous> (/app/node_modules/docker-secret/dist/index.js:28:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/utils/init/initDockerSecrets.js:1:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
---

**Steps to reproduce:**

1. Start with a base k3s installation.
2. Deploy the following resource to the cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame
spec:
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      volumes:
        - name: flame-volume
          emptyDir: {}
      containers:
      - name: flame
        image: pawelmalak/flame:multiarch2.1.1
        ports:
        - containerPort: 5005
        volumeMounts:
        - mountPath: /app/data
          name: flame-volume
        env:
        - name: PASSWORD
          value: flame_password
```
3. Watch the logs of the newly-deployed pod.

**Comment by pawelmalak** [comment]
I can't test it right now but can you pull `pawelmalak/flame:dev` and check if anything has changed?

**Comment by jojotastic777** [comment]
No apparent change, it seems like:
```
node:internal/fs/utils:344
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at /app/node_modules/docker-secret/dist/index.js:17:39
    at Array.forEach (<anonymous>)
    at getSecrets (/app/node_modules/docker-secret/dist/index.js:14:15)
    at Object.<anonymous> (/app/node_modules/docker-secret/dist/index.js:28:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/utils/init/initDockerSecrets.js:1:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

**Comment by c0depool** [comment]
Getting the same error on microk8s as well. Was working fine on v2.1.0.

**Comment by kooskaspers** [comment]
Same problem here.
Back to 2.1.0.

**Comment by Seanland** [comment]
Getting the exact same error here.  If it helps, these are my environment details:

App version [e.g. v1.7.4]: 2.1.1
Platform [e.g. amd64, arm64, arm/v7]: amd64
Docker image tag [e.g. latest, multiarch]: latest

I am running mine on a bare-metal k8s cluster using kubeadm

**Comment by IDevJoe** [comment]
App version [e.g. v1.7.4]: 2.1.1
Platform [e.g. amd64, arm64, arm/v7]: ard64
Docker image tag [e.g. latest, multiarch]: multiarch

Same issue.

**Comment by IDevJoe** [comment]
You (theoretically) should be able to work around this issue by disabling the service account token like so:

```apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  automountServiceAccountToken: false
  ...

**Comment by Seanland** [comment]
@IDevJoe Your theory worked (at least for me).  Thanks for the workaround.

**Comment by odinsride** [comment]
Just want to mention I am encountering this error as well, but on openSUSE Leap Server, using a docker-compose `.env` file:

```
Docker version 20.10.9-ce, build 79ea9d308018
docker-compose version 1.25.1, build a82fef0
```

```
  flame:
    image: pawelmalak/flame:2.1.0
    container_name: flame
    volumes:
      - ${APPDATA_BASE}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5005:5005"
    restart: unless-stopped
```
