### ISSUE TITLE
[BUG] Applications fail to load - [ERROR] containers.filter is not a function

### ISSUE THREAD

**Issue by cbenning** [pawelmalak/flame#244]
**Deployment details:**
- App version [e.g. v1.7.4]: v2.1.1 
- Platform [e.g. amd64, arm64, arm/v7]: amd64 
- Docker image tag [e.g. latest, multiarch]: 2.1.1

---

**Bug description:**

After logging in, the Applications section just loads forever. When I do docker logs -f flame I see:

`[ERROR] containers.filter is not a function`

repeated each time I refresh the page.

---

**Steps to reproduce:**

Docker-compose:

```
  flame:
    image: pawelmalak/flame:2.1.1
    container_name: flame
    volumes:
      - /<path>/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 80:5005
    environment:
      - PASSWORD=<password>
    restart: unless-stopped
```

1. docker-compose up -d
2. Open http://<ip>:80 in browser
3. Enter password
4. Applications section loads forever
