### ISSUE TITLE
[FEATURE] Crop or hide URL in Applications

### ISSUE THREAD

**Issue by nicolaibob** [pawelmalak/flame#258]
Some of my URLs, used for my application are long - would be nice, if one could hide the URL and/OR If URLs could be reduce to only show the domain name or X chars followed by ...

**Comment by Teraskull** [comment]
CSS saves the day!

Dynamic resizing truncates the Title and URL:

![image](https://user-images.githubusercontent.com/24798198/146475040-e0a735a2-0700-4ef6-8946-b39a40e2fb18.png)

![image](https://user-images.githubusercontent.com/24798198/146475156-1991d2e4-2276-4461-9fd1-29a1e67263d8.png)

```css
/* Truncate Title and URL */
.AppCard_AppCardIcon__8ZZTq {
    min-width: 35px;
}
.AppCard_AppCard__1V2_0 {
    min-width: 0
}
.AppCard_AppCardDetails__tbAhY {
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}
```

Here is my [full theme](https://gist.github.com/Teraskull/1e1c30923617b28f6fc0d331c1d854e9) if you're interested.
