### ISSUE TITLE
[BUG] Chrome/Firefox asks for Authentication (Browser popup)

### ISSUE THREAD

**Issue by jonathanmmm** [pawelmalak/flame#272]
Hi,

I am using the docker image (with no internet access, internal network) behind an nginx reverse proxy.

In Brave (Chromium Based) I don't get this pop up (asking for username and password and entering only the correct password doesn't work). The interface works, I just have to click cancel. But I was logged in at some point in Brave (deleting the cookies, created the same result).

My nginx config:
```
set $upstream_flame_container flame-container:5005;
location / {
proxy_pass http://$upstream_flame_container;
 proxy_set_header X-Real-IP  $remote_addr;
 proxy_set_header X-Forwarded-For $remote_addr;
 proxy_set_header Host $host;
}
```

```
version: '3.6'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame-container
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PASSWORD=somesecretString
    restart: unless-stopped
    networks:
      - flameproxy:

networks:
 flameproxy:
  external: true
```

flameproxy is an internal docker network, so that nginx (also in docker) can access it and flame doesn't have any internet access.
