### ISSUE TITLE
[BUG] Environment variable `PASSWORD_FILE` isn't considered

### ISSUE THREAD

**Issue by rperpe** [pawelmalak/flame#275]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.2.0
- Platform [e.g. amd64, arm64, arm/v7]: amd64
- Docker image tag [e.g. latest, multiarch]: 2.2.0

---

**Bug description:**

Environment variable `PASSWORD_FILE` isn't considered. Instead it looks like `/run/secrets` is scanned and contents are mapped to env variables.

---

**Steps to reproduce:**

1. Set `PASSWORD_FILE` env variable e.g. to `/run/secrets/flame-password` (contains "averysecretpassword")
2. Bring the container up
3. Observe the logs and see that `FLAME-PASSWORD` instead of `PASSWORD` gets set
4. Try to login with "averysecretpassword"
5. Login fails

Expected behaviour would be that `PASSWORD` gets to set of contents of the file referenced in `PASSWORD_FILE`. No matter where `PASSWORD_FILE` points to.

**Comment by enricomarogna** [comment]
Same error

**Comment by HerrFrutti** [comment]
for me docker secrets doesn't seem to work...
My log shows:
```
[2022-01-06 13:00:18.615 UTC+0] [INFO] FLAME_PWD was overwritten with docker secret value
[2022-01-06 13:00:18.649 UTC+0] [INFO] Server is running on port 5005 in production mode
[2022-01-06 13:00:28.201 UTC+0] [ERROR] Invalid credentials
[2022-01-06 13:00:18.644 UTC+0] [INFO] Connected to database
[2022-01-06 13:00:18.649 UTC+0] [INFO] Socket: listen
[2022-01-06 13:00:28.201 UTC+0] [ERROR] Invalid credentials
```

**Comment by pawelmalak** [comment]
Can you show your docker-compose files?

**Comment by HerrFrutti** [comment]
```yaml
version: '2.1'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ./data:/app/data
      #- /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
#    ports:
#      - 5005:5005
    restart: unless-stopped
    environment:
       PASSWORD: my-secret-pass
       PASSWORD_FILE: /run/secrets/FLAME_PWD
    secrets:
      - FLAME_PWD
    networks:
      - reverseproxy-nw
networks:
  reverseproxy-nw:
    external: true
secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ">
  FLAME_PWD:
    file: .secrets/flame_pwd
```
that's my current docker-compose file. The contents of the FLAME_PWD match the value off PASSWORD.

If I run the compose file like this:
```yaml
version: '2.1'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ./data:/app/data
      #- /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
#    ports:
#      - 5005:5005
    restart: unless-stopped
    environment:
       PASSWORD_FILE: /run/secrets/FLAME_PWD
    secrets:
      - FLAME_PWD
    networks:
      - reverseproxy-nw
networks:
  reverseproxy-nw:
    external: true
secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ">
  FLAME_PWD:
    file: .secrets/flame_pwd
```
My Password isn't correct...

**Comment by KillerTic** [comment]
Got the same issue. Could it be, that the secret file has to be called password? Would be quite inconvienient in a larger compose stack.

**Comment by rperpe** [comment]
@KillerTic Exactly this is the case. Sorry if I didn't make this clear enough in initial description.

**Comment by KillerTic** [comment]
Oh okay.
This is a little inconvienient. I have currently 14 secrets of which 8 are passwords.
If I would have another docker needing it to be password as well, I would have a problem. 

I am used to, that you can just name the file whatever you want.
If that is not possible here, could the variable then at least be called "flame_password"?

**Comment by ahmaddxb** [comment]
> Oh okay. This is a little inconvienient. I have currently 14 secrets of which 8 are passwords. If I would have another docker needing it to be password as well, I would have a problem.
> 
> I am used to, that you can just name the file whatever you want. If that is not possible here, could the variable then at least be called "flame_password"?

I second this, greatly appreciated it if you could make the change

**Comment by dtypo** [comment]
Up for this, same identical problem.

**Comment by tillo** [comment]
For those who stumble upon the same issue, I've written a quick and dirty patch for this.

Relevant sections of my flame service in docker-compose.yml:
```yaml
        environment:
            - PASSWORD_SECRET=flame_password
        secrets:
            - flame_password
        volumes:
            - '/root/flame-patches:/mnt/patches'
        command: /bin/sh -c 'apk add --no-cache patch && patch -N -t -p2 -i /mnt/patches/password_secret.patch /app/utils/init/initDockerSecrets.js; chown -R node /app/data && node server.js'
```

And my /root/flame-patches/password_secret.patch:
```diff
--- utils-orig/init/initDockerSecrets.js
+++ utils/init/initDockerSecrets.js
@@ -9,6 +9,13 @@
     for (const property in secrets) {
       const upperProperty = property.toUpperCase();

+      if (property == process.env["PASSWORD_SECRET"]) {
+
+        process.env["PASSWORD"] = secrets[property];
+
+        logger.log(`PASSWORD was overwritten with ${property} docker secret value`);
+      }
+
       process.env[upperProperty] = secrets[property];

       logger.log(`${upperProperty} was overwritten with docker secret value`);
```

This lets you use any secret name, like flame_password in my example, to be provided through the PASSWORD_SECRET environment variable.

This patching technique will avoid having to maintain your own image, until the patch breaks and needs to be adapted to new code.
