### ISSUE TITLE
Hide Application URLs

### ISSUE THREAD

**Issue by MichiFr** [pawelmalak/flame#276]
Hi!

Maybe I missed the obvious, but is there any setting to hide the URL that is shown under each applications name?

Thx,
Michael

**Comment by KevBelisle** [comment]
You can hide it with this custom CSS:

```CSS
.AppCard_AppCardDetails__tbAhY > span {
  display: none;
}
```
