### ISSUE TITLE
[Feature Request] way to edit wording of 'Applications' and 'Bookmarks'

### ISSUE THREAD

**Issue by itsinART** [pawelmalak/flame#339]
first of all, i'm a big fan - great job :)

it would be nice to name the categories 'Applications' and 'Bookmarks' as wanted. 
or did i miss any css workaround to archieve this?

"SectionHeadline_SectionHeadline__2gmr_">**Applications**
"SectionHeadline_SectionHeadline__2gmr_">**Bookmarks**

**Comment by leonbeon** [comment]
A native way would be great! For now, here is my CSS workaround (translating into German in my case):

```css
:root {
  --name-bookmarks: "Lesezeichen";
  --name-applications: "Anwendungen";
}

/****************************************************/
/* Translate h2 headings */
/* - - - - - - - - - - - - - - - - - - - - - - - - -*/
a[href="/applications"] > h2,
a[href="/bookmarks"] > h2 {
    visibility: hidden;
}
a[href="/applications"] > h2::before {
    content: var(--name-applications);
    visibility: visible;
}
a[href="/bookmarks"] > h2::before {
    content: var(--name-bookmarks);
    visibility: visible;
}

```
