### ISSUE TITLE
Provide class names for major elements for custom CSS

### ISSUE THREAD

**Issue by leonbeon** [pawelmalak/flame#435]
Currently, class names get auto generated, leaving us to think of some _creative_ ways to access selectors for custom css implementation and confusion (see #434, #433). I propose we add a simple class name to every major element. For example, currently the app grid for applications looks like this:

```html
<div class="AppGrid_AppGrid__33iLW">
</div>
```
The `__33iLW` suffix will be changed with every build, making the class name unreliable for targeting the element between updates. We could change it to something like

```html
<div class="applications-app-grid AppGrid_AppGrid__33iLW">
</div>
```

with a static class name. I think every element with an auto generated name (e.g. `.Layout_Container__2Hv3J`, `.Header_Header__2oavH`,  `.BookmarkGrid_BookmarkGrid__26LlR`, `.Home_SettingsButton__Qvn8C`)would benefit from the static class names, as well as
- the search bar `div`
- `<a href="/applications">`
- `<a href="/bookmarks">`

For reference how complicated this can get without, this is my current setup to add a "Search:" prefix in front of the search bar:
<details>
<summary>Open me</summary>

```css
:root {
  --name-search: "Search";
}

#root > div:first-child > div:first-child {
    display: flex;
}
#root > div:first-child > div:first-child::before {
    content: var(--name-search) ':';
    margin-bottom: 20px;
    margin-right:0.33rem;
    padding: 10px 0;
    color: var(--color-accent);
}

```
</details>
