### ISSUE TITLE
[BUG] Support for more Kubernetes ingress annotations

### ISSUE THREAD

**Issue by djjudas21** [pawelmalak/flame#456]
**Deployment details:**
- App version: v2.3.1
- Platform: amd64
- Docker image tag: `docker.io/pawelmalak/flame:multiarch2.3.1`

---

**Bug description:**

I am using the Kubernetes integration to populate my Flame dashboard. It is working well but I would like support for more Ingress annotations, to enable the setting of description and toggle visibility.

I would like to see support for the following annotations:

```yaml
annotations:
  flame.pawelmalak/description: My app is awesome
  flame.pawelmalak/visibility: true
```

With these new annotations, I would be able to complete all configuration automatically, without the UI menus :slightly_smiling_face: 

Thanks for your consideration, and for making an awesome piece of software :100:
