### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by sdenike** [pawelmalak/flame#482]
Since this project seems more or less dead based on the lack of updates, is there a more current/active on that someone forked?

**Comment by rightsaidfred99** [comment]
It died years aga and has serious security concerns

**Comment by dillacorn** [comment]
I'd like an active fork as well..

**Comment by Jdemuren** [comment]
> It died years aga and has serious security concerns

what do you mean security concerns? Can you please enlighten me, as this is still my main homepage

**Comment by dillacorn** [comment]
> > It died years aga and has serious security concerns
> 
> what do you mean security concerns? Can you please enlighten me, as this is still my main homepage

If you're exposing it to the web - it's possible there are security concerns sense it hasn't been updated in so long.. If you're using it via a tunnel privately not a big deal.. If you're sharing the page for others to use than I'd suggest using an active fork.

I use fdarveau fork now.. Personally still love this simplistic light weight homepage and wasn't willing to drop it but this guy is keeping it alive.

https://github.com/fdarveau/flame

My compose file:

https://github.com/dillacorn/deb-omv-dots/blob/main/docker/flame/docker-compose_example.yml

**Comment by spiicytuna** [comment]
** NOT TO TAKE AWAY FROM  [fdarveau](https://github.com/fdarveau/flame) => when replying I noticed the @dillacorn post ** 

I wanted to run this on my VPS as well but noticed when building MANY security updates have happened since the last update to this repo in over 2 years... so I forked it, applied [security updates](https://github.com/spiicytuna/flame/commit/a8559b4e509e00e33f3947b5e9495c4e90759e6f), to a place that ***_I_*** felt OK to run on **_my_** VPS (npm audit doesn't report anything else), oh and for fun, I and added the mdi newest icons.  Feel free to point your docker compose to `image: ghcr.io/spiicytuna/flame:stable` to use.  No warranty offered haha 😄 

If you want to be really wild, for my own personal use case, I added categories to Applications whereas that was only available to Bookmarks in this repo, and weather based on geoip.  If you want to be wild use `ghcr.io/spiicytuna/flame-dev:latest` but it's a work in progress so things like "update available" pop-up and such--but works well enough to be _my daily driver._

```
# npm audit --omit=dev --legacy-peer-deps
found 0 vulnerabilities
```

**Comment by rightsaidfred99** [comment]
> > It died years aga and has serious security concerns
> 
> what do you mean security concerns? Can you please enlighten me, as this is still my main homepage

This issue for one

https://github.com/pawelmalak/flame/issues/465

But likely many more. But as others mentioned, no big deal if you just run this locally in controlled environments

**Comment by icmonsters** [comment]
> ghcr.io/spiicytuna/flame:stable

I've been trying to pull your image and keep getting denied. Tried everything so I wonder if permissions are correct your end?

`✘ flame Error Head "https://ghcr.io/v2/spiicytuna/flame/manifests/stable": denied:...              3.3s 
Error response from daemon: Head "https://ghcr.io/v2/spiicytuna/flame/manifests/stable": denied: denied`

**Comment by spiicytuna** [comment]
I'll switch it to public later today but in the meantime, are you logged in?  
[Github] settings > Developer settings > Personal access tokens > Tokens (classic)

```
docker login ghcr.io   => (need to create an access token in lieu of password)
docker pull ghcr.io/spiicytuna/flame:latest
```

> `✘ flame Error Head "https://ghcr.io/v2/spiicytuna/flame/manifests/stable": denied:... 3.3s Error response from daemon: Head "https://ghcr.io/v2/spiicytuna/flame/manifests/stable": denied: denied`

**Comment by icmonsters** [comment]
Yep, logged in. Just pulled successfully. Thank you.

**Comment by dillacorn** [comment]
@spiicytuna Hey I tried moving over to your fork but I hit a snag I just realized @fdarveau implemented into his fork. That being folders/categories in Applications section.. Can you implement this into your fork as well?

I found the commit:
https://github.com/pawelmalak/flame/commit/c80e4257ff194afe50a4de3652adfa33ce609fd8

<img width="1243" height="540" alt="Image" src="https://github.com/user-attachments/assets/317d1b24-3012-44e6-8446-693232a989a6" />

**Comment by varadins** [comment]
@spiicytuna Thanks for stoking the fire on this.  I'm attempting to try out the tuna combo, and I'm hitting a snag.

```
[2025-09-09 20:49:25.761 UTC+0] [INFO] Custom SECRET environment variable found. Using it.
[2025-09-09 20:49:26.271 UTC+0] [INFO] SQLite PRAGMA foreign_keys = ON
[2025-09-09 20:49:26.271 UTC+0] [INFO] Migrations on disk: 00_initial.js, 01_new-config.js, 02_resource-access.js, 03_weather.js, 04_bookmarks-order.js, 05_app-description.js, 2025-08-ensure-apps-category-fk.js, 2025-09-add-category-abbreviation.js, 2025-09-add-category-collapse.js
[2025-09-09 20:49:26.287 UTC+0] [INFO] Executed migrations: 00_initial.js, 01_new-config.js, 02_resource-access.js, 03_weather.js, 04_bookmarks-order.js, 05_app-description.js  
[2025-09-09 20:49:26.294 UTC+0] [INFO] Pending migrations: 2025-08-ensure-apps-category-fk.js, 2025-09-add-category-abbreviation.js, 2025-09-add-category-collapse.js
[2025-09-09 20:49:26.294 UTC+0] [INFO] Executing pending migrations
[2025-09-09 20:49:26.309 UTC+0] [ERROR] Unable to connect to the database: SQLITE_ERROR: table categories has no column named section
```

```
services:
  flame:
    image: ghcr.io/spiicytuna/flame-dev:latest
    container_name: tunacombo
    restart: unless-stopped
    ports:
      - "5006:5005"
    volumes:
      - /home/docker/docker/tunacombo:/app/data
      # - /path/to/favicon.ico:/app/public/icons/favicon.ico  #  optional change to your own favicon.co
      # - /var/log/flame-dash:/app/log  #  optional external access.log remote logging or fail2ban
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    environment:
      - PASSWORD=REDACTED
      # - WEATHER_CACHE_HOURS=6  #  optional to cut down calls to weather api
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:5005/health"]
      interval: 60s
      timeout: 10s
      retries: 3
```
