### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by DevolgaDevs** [pawelmalak/flame#6]
Hi,

Is it possible to get a docker compose file ?

Thanks

**Comment by pawelmalak** [comment]
Hi. I just started learning Docker this week so there is still a lot things I need to learn about it but I thought `docker-compose.yml` is only needed for running multiple containers at once. Why would we need one here?

**Comment by firestrife23** [comment]
Here's mine, you may need to edit to your preference.

```
  flame:
    container_name: flame
    image: pawelmalak/flame:latest
    volumes:
      - /usr/share/flame:/app/data
    ports:
      - 5005:5005
    restart: unless-stopped
```
